# Generated by Django 2.0.3 on 2019-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pizza_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_available',
            field=models.CharField(default='YES', max_length=64),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_img',
            field=models.CharField(default='pizza/img/', max_length=600),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='pizza_add_ons',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='pizza_size',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.RemoveField(
            model_name='pizza_order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='pizza',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
