# Generated by Django 2.0.3 on 2019-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190921_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingrediants',
            field=models.CharField(default='', max_length=900),
        ),
    ]
