# Generated by Django 2.0.3 on 2019-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190921_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_order',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='pizza',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
