# Generated by Django 2.0.3 on 2019-09-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190921_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
