# Generated by Django 2.1.5 on 2019-11-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_value_Q',
            field=models.IntegerField(default=0),
        ),
    ]
