# Generated by Django 2.1.5 on 2019-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza_order',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='pizza_order',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizza_order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza_order',
            name='username',
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='cart_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza_order',
            name='status',
            field=models.CharField(default='waiting', max_length=32),
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_toppings',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='address',
            field=models.CharField(default='NO_ADDRESS', max_length=900),
        ),
    ]
