# Generated by Django 2.1.5 on 2019-11-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191114_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='topping_img/')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza_order',
            name='cart_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
