# Generated by Django 2.1.5 on 2019-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191119_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='available',
            field=models.CharField(default='ON', max_length=3),
        ),
    ]
