# Generated by Django 2.1.5 on 2019-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191120_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.IntegerField(default=0),
        ),
    ]
