# Generated by Django 2.0.3 on 2019-09-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190921_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='pizza_order',
            old_name='pizza_add_ons',
            new_name='add_ons',
        ),
        migrations.RenameField(
            model_name='pizza_order',
            old_name='pizza_size',
            new_name='size',
        ),
    ]
