# Generated by Django 2.1.5 on 2019-11-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191119_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='available',
            field=models.CharField(default='YES', max_length=3),
        ),
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.ImageField(help_text='Topping Image', upload_to='topping_img/'),
        ),
    ]
